#ifndef _CONFIG_HPP_
#define _CONFIG_HPP_
#include "raylib.h"

const int SCREEN_WIDTH {1280}, SCREEN_HEIGHT {720};
const int PADDLE_WIDTH {30}, PADDLE_HEIGHT {200};
const int BALL_SIZE {20};

const int PADDLE_WALL_DIST {100};
const float PADDLE_START_Y {(SCREEN_HEIGHT / 2) - (PADDLE_HEIGHT / 2)};
const float BALL_START_X {(SCREEN_WIDTH / 2) - (BALL_SIZE / 2)}, BALL_START_Y {(SCREEN_HEIGHT / 2) - (BALL_SIZE / 2)};

const int FRAME_TARGET {144};

const float PADDLE_SPEED {500}, BALL_SPEED {300};
const float BALL_VELOCITY_OFFSET {200};
const float BALL_SPEED_INCREASE {10};

const float COUNT_DOWN_TIME {3};

const int SCORE_TEXT_TOP_OFFSET {10}, SCORE_TEXT_BETWEEN_OFFSET {100};
const int SMALL_FONT_SIZE {40}, MEDIUM_FONT_SIZE {60}, LARGE_FONT_SIZE {100};
const int MEDIUM_FONT_SHADOW {5};

const Color BALL_COLOR {255,50,50,255};

#endif